source 'http://rubygems.org'
gem 'rails', '3.2.11'

gem 'jquery-rails'
gem 'bcrypt-ruby','~>3.0.0'
gem 'rabl'
gem 'faker'
gem 'squeel'
gem 'seed_dump'
gem 'will_paginate'
gem 'paperclip','~> 3.0'
gem 'multi_json'
gem 'aws-sdk'
gem 'jquery-datatables-rails', git: 'git://github.com/rweng/jquery-datatables-rails.git'
gem 'jquery-ui-rails'

group :development, :test do
  gem 'sqlite3', '1.3.5'
  gem 'rspec-rails', '2.11.0'
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '4.1.0'
  gem 'guard-rspec', '1.2.1'
  gem 'rb-fsevent', '~> 0.9'
end

group :development do 
  gem 'annotate', '2.5.0'
end

group :assets do
  gem 'sass-rails', '~> 3.2'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
  gem 'bootstrap-sass', '~> 3.0.0.0.rc'
end

group :test do
  gem 'database_cleaner', '0.7.0'
  gem 'launchy', '2.1.0'
end

group :production do
  gem 'pg', '0.12.2'
  gem 'rails_12factor'
end