source 'http://rubygems.org'
ruby '2.0.0'

gem 'rails', '3.2.11'

gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "twitter-bootstrap-rails", '2.2.4'
gem "jquery-rails"
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'rabl'
gem 'faker'
gem "squeel"
gem 'will_paginate'
gem 'paperclip'
gem 'multi_json'
gem 'aws-sdk'
gem 'jquery-datatables-rails', git: 'git://github.com/rweng/jquery-datatables-rails.git'
gem 'jquery-ui-rails'
group :development, :test do
  gem 'sqlite3', '1.3.5'
  # Testing Gems
  gem 'rspec-rails', '2.11.0'
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '4.1.0'
  gem 'guard-rspec', '1.2.1'
  gem 'rb-fsevent', '~> 0.9'
end

group :development do 
  gem 'annotate', '2.5.0'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem "therubyracer", "~> 0.12.0"
  gem 'sass-rails', '~> 3.2'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
  gem 'bootstrap-sass', '~> 2.0.2'
end

group :test do
  gem 'database_cleaner', '0.7.0'
  #  It opens your default web browser upon failed integration specs to show you what your application is rendering.
  gem 'launchy', '2.1.0' #
end

group :production do
  gem 'pg', '0.12.2'
end