# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Charity.create!([
  { :charityid => 1, :name_lowercase => "orant", :name => "ORANT", :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08" }
])

Medication.create!([
  { :medId => 1, :name => "Clotrimazole (Clonex Cream)", :numContainers => 33, :tabletsPerContainer => 49, :expiration => "1997-10-04", :doseOfTablets => 20, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 2, :name => "Co-Amoxiclav/Augmentin Tablet (Cledomox)", :numContainers => 52, :tabletsPerContainer => 36, :expiration => "1970-06-18", :doseOfTablets => 42, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 3, :name => "Ciprofloxacin", :numContainers => 36, :tabletsPerContainer => 36, :expiration => "1988-03-20", :doseOfTablets => 14, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 4, :name => "Cimetidine Tablets (Cismetine)", :numContainers => 50, :tabletsPerContainer => 40, :expiration => "1977-02-05", :doseOfTablets => 39, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 5, :name => "Diphenhydramine (Banophen)", :numContainers => 41, :tabletsPerContainer => 37, :expiration => "2012-07-04", :doseOfTablets => 26, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 6, :name => "Co-Trimoxazole/Bactrim (unitrim)", :numContainers => 59, :tabletsPerContainer => 18, :expiration => "1981-10-27", :doseOfTablets => 38, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 7, :name => "Cephalexin", :numContainers => 35, :tabletsPerContainer => 46, :expiration => "1982-03-22", :doseOfTablets => 49, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 8, :name => "Cephalexin", :numContainers => 34, :tabletsPerContainer => 42, :expiration => "2009-10-11", :doseOfTablets => 15, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 9, :name => "Cephalexin", :numContainers => 31, :tabletsPerContainer => 17, :expiration => "1985-09-10", :doseOfTablets => 15, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 10, :name => "Azithromycin (Uzet)", :numContainers => 59, :tabletsPerContainer => 14, :expiration => "1987-11-02", :doseOfTablets => 47, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 11, :name => "Amoxicillin (Medamox)", :numContainers => 31, :tabletsPerContainer => 29, :expiration => "1990-09-04", :doseOfTablets => 17, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 12, :name => "Amoxicillin (Medamox)", :numContainers => 55, :tabletsPerContainer => 30, :expiration => "1980-06-17", :doseOfTablets => 44, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 13, :name => "Albezole (Albendazole Tablets)", :numContainers => 48, :tabletsPerContainer => 36, :expiration => "2009-08-29", :doseOfTablets => 23, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 14, :name => "Inhalation Solution (Albuterol Sulfate .63 mg)", :numContainers => 41, :tabletsPerContainer => 21, :expiration => "2002-04-06", :doseOfTablets => 47, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 15, :name => "Inhalation Solution (Ipratorpium Bromide .5mg and Albuterol Sulfate 3.0mp)", :numContainers => 60, :tabletsPerContainer => 30, :expiration => "1996-11-24", :doseOfTablets => 50, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 16, :name => "Aspirin (St. Jospeh)", :numContainers => 48, :tabletsPerContainer => 15, :expiration => "1981-12-20", :doseOfTablets => 17, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 17, :name => "Aspirin (Equate)", :numContainers => 53, :tabletsPerContainer => 45, :expiration => "1997-01-10", :doseOfTablets => 38, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 18, :name => "Acryclovir Cream (Zovirax)", :numContainers => 43, :tabletsPerContainer => 11, :expiration => "1994-10-24", :doseOfTablets => 45, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 19, :name => "Acetamiophene (Mapap)", :numContainers => 54, :tabletsPerContainer => 25, :expiration => "1989-06-07", :doseOfTablets => 41, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08", :notes => nil },
  { :medId => 20, :name => "Clotrimazole (Clonex Cream)", :numContainers => 51, :tabletsPerContainer => 11, :expiration => "2000-11-26", :doseOfTablets => 20, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 21, :name => "Co-Amoxiclav/Augmentin Tablet (Cledomox)", :numContainers => 44, :tabletsPerContainer => 26, :expiration => "1983-06-13", :doseOfTablets => 20, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 22, :name => "Ciprofloxacin", :numContainers => 45, :tabletsPerContainer => 15, :expiration => "1991-07-24", :doseOfTablets => 28, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 23, :name => "Cimetidine Tablets (Cismetine)", :numContainers => 50, :tabletsPerContainer => 47, :expiration => "1972-06-27", :doseOfTablets => 12, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 24, :name => "Diphenhydramine (Banophen)", :numContainers => 60, :tabletsPerContainer => 28, :expiration => "1970-05-29", :doseOfTablets => 13, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 25, :name => "Co-Trimoxazole/Bactrim (unitrim)", :numContainers => 34, :tabletsPerContainer => 48, :expiration => "1996-09-01", :doseOfTablets => 48, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 26, :name => "Cephalexin", :numContainers => 47, :tabletsPerContainer => 34, :expiration => "1980-07-19", :doseOfTablets => 16, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 27, :name => "Cephalexin", :numContainers => 31, :tabletsPerContainer => 15, :expiration => "1984-11-23", :doseOfTablets => 43, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 28, :name => "Cephalexin", :numContainers => 51, :tabletsPerContainer => 21, :expiration => "1973-03-19", :doseOfTablets => 26, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 29, :name => "Azithromycin (Uzet)", :numContainers => 35, :tabletsPerContainer => 39, :expiration => "1996-10-12", :doseOfTablets => 40, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 30, :name => "Amoxicillin (Medamox)", :numContainers => 40, :tabletsPerContainer => 15, :expiration => "1972-11-14", :doseOfTablets => 33, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 31, :name => "Amoxicillin (Medamox)", :numContainers => 30, :tabletsPerContainer => 36, :expiration => "2002-12-02", :doseOfTablets => 30, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 32, :name => "Albezole (Albendazole Tablets)", :numContainers => 58, :tabletsPerContainer => 25, :expiration => "2006-07-25", :doseOfTablets => 14, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 33, :name => "Inhalation Solution (Albuterol Sulfate .63 mg)", :numContainers => 35, :tabletsPerContainer => 34, :expiration => "1997-11-16", :doseOfTablets => 43, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 34, :name => "Inhalation Solution (Ipratorpium Bromide .5mg and Albuterol Sulfate 3.0mp)", :numContainers => 60, :tabletsPerContainer => 32, :expiration => "1987-10-18", :doseOfTablets => 50, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 35, :name => "Aspirin (St. Jospeh)", :numContainers => 30, :tabletsPerContainer => 11, :expiration => "1971-03-12", :doseOfTablets => 40, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 36, :name => "Aspirin (Equate)", :numContainers => 42, :tabletsPerContainer => 50, :expiration => "1995-10-19", :doseOfTablets => 43, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 37, :name => "Acryclovir Cream (Zovirax)", :numContainers => 54, :tabletsPerContainer => 25, :expiration => "2000-10-26", :doseOfTablets => 40, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil },
  { :medId => 38, :name => "Acetamiophene (Mapap)", :numContainers => 46, :tabletsPerContainer => 17, :expiration => "1998-09-25", :doseOfTablets => 49, :status => 1, :created_at => "2013-11-24 00:30:09", :updated_at => "2013-11-24 00:30:09", :notes => nil }
])



User.create!([
  { :userid => 1,:userName => "admin", :password => "foobar", :password_confirmation => "foobar", :firstName => "Ray", :lastName => "Misomali", :email => "admin@example.com", :charityid => "1", :question => "1", :answer => "elpidio valdes", :userType => 0, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08"},
  { :userid => 2,:userName => "epere250", :password => "foobar", :password_confirmation => "foobar", :firstName => "Ernesto", :lastName => "Perez", :email => "epere250@fiu.edu", :charityid => "1", :question => "1", :answer => "elpidio valdes", :userType => 0, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08"}
])


