# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Charity.create!([
  { :charityid => 1, :name => "ORANT", :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08" }
])

User.create!([
  { :userid => 1,:userName => "admin", :password => "foobar", :password_confirmation => "foobar", :firstName => "Ray", :lastName => "Misomali", :email => "admin@example.com", :charityid => 1, :question => "1", :answer => "elpidio valdes", :userType => 0, :status => 1, :created_at => "2013-11-24 00:03:08", :updated_at => "2013-11-24 00:03:08"},
])


